title = "secrets.toml"

[mysql]
user = "the-company"
password = "Dancingb4n4n4s!"

[mailer]
url = "https://mailer.thecompany.com"
apikey = "Th1Si5Th3Ap1Ke4"

[steam]
steamid = "0:1:4553128"
password = "L33T supa H4X0R"
